spring.application.name=payment-transfer-api
spring.datasource.url=jdbc:postgresql://localhost:15432/payments
spring.datasource.username=payments_user
spring.datasource.password=payments_local_password
management.endpoint.health.show-details=always
spring.jpa.hibernate.ddl-auto=validate
spring.devtools.restart.enabled=false
